apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "springkube-deploy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "springkube"
      app.kubernetes.io/version: "1.0-SNAPSHOT"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "springkube"
        app.kubernetes.io/version: "1.0-SNAPSHOT"
    spec:
      containers:
      - name: "springkube"
        image: "gustavoftins/springkube"
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "750m"

